# PostgreSQL datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${POSTGRES_URL:jdbc:postgresql://localhost/petclinic}
quarkus.datasource.username=${POSTGRES_USER:petclinic}
quarkus.datasource.password=${POSTGRES_PASS:petclinic}

# SQL init
quarkus.hibernate-orm.sql-load-script=db/postgres/schema.sql,db/postgres/data.sql
