# PostgreSQL configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${POSTGRES_URL:jdbc:postgresql://localhost/petclinic}
quarkus.datasource.username=${POSTGRES_USER:petclinic}
quarkus.datasource.password=${POSTGRES_PASS:petclinic}
quarkus.hibernate-orm.database.generation=drop-and-create
