# MySQL configuration
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${MYSQL_URL:jdbc:mysql://localhost/petclinic}
quarkus.datasource.username=${MYSQL_USER:petclinic}
quarkus.datasource.password=${MYSQL_PASS:petclinic}
quarkus.hibernate-orm.database.generation=drop-and-create
