# MySQL datasource
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${MYSQL_URL:jdbc:mysql://localhost/petclinic}
quarkus.datasource.username=${MYSQL_USER:petclinic}
quarkus.datasource.password=${MYSQL_PASS:petclinic}

# SQL init
quarkus.hibernate-orm.sql-load-script=db/mysql/schema.sql,db/mysql/data.sql
