# Datasource - H2 default
quarkus.datasource.db-kind=h2
%prod.quarkus.datasource.jdbc.url=jdbc:h2:mem:petclinic
%prod.quarkus.datasource.username=sa
%prod.quarkus.datasource.password=

# Hibernate ORM
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
quarkus.hibernate-orm.jdbc.statement-batch-size=16
quarkus.hibernate-orm.sql-load-script=import.sql

# Logging
quarkus.log.category."org.springframework".level=INFO

# Qute template engine
quarkus.qute.strict-rendering=false
quarkus.qute.property-not-found-strategy=output-original

# i18n
quarkus.default-locale=en

# Static resources cache
quarkus.http.static-resources.caching-enabled=true
